<?php
namespace models;
include_once '../../models/api.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-08 at 21:12:47.
 */
class ApiTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Api
     */
    protected $boardingPassesArray;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $value = '{"boardingPasses":[
 {"pointA":"Amman","pointB":"Jerash","type":"Bus","info":"No seat assigned"}
,{"pointA":"Jerash","pointB":"Dammam","type":"Flight","info":"Flight number AK47 Gate 15B"}
,{"pointA":"Dammam","pointB":"Cairo","type":"Flight","info":"Flight number M16 Terminal 2"}
,{"pointA":"Cairo","pointB":"Riyadh","type":"Train","info":"Seat 34"}
,{"pointA":"Riyadh","pointB":"Irbid","type":"Bus","info":"No seat assigned"}
,{"pointA":"Zarqa","pointB":"Irbid","type":"Flight","info":"D3"}
,{"pointA":"Zarqa","pointB":"Demuscus","type":"Flight","info":"Flight Number SY15 Gate 5"}
,{"pointA":"Rome","pointB":"Demuscus","type":"Flight","info":"Flight Number SY15 Gate 5, Luggage will follow"}
,{"pointA":"Rome","pointB":"Alain","type":"Ship","info":"Dock 4, seat 15A"}
,{"pointA":"Jeddah","pointB":"Alain","type":"Train","info":"First class, seat A3"}
,{"pointA":"Mekka","pointB":"Jeddah","type":"Taxi","info":"Booking reference XV3456"}
,{"pointA":"Mekka","pointB":"Sharm","type":"Flight","info":"Flight number 30A Seat 33C"}
,{"pointA":"Sharm","pointB":"Birut","type":"Train","info":"You dont have a seat jump to the cargo carriages."}
,{"pointA":"Dubai","pointB":"Birut","type":"Flight","info":"Flight Number 666AE First Class Seat 4A"}
]}';
        $this->boardingPassesArray = new Api($value);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers models\Api::sortTrips
     * @todo   Implement testSortTrips().
     */
    public function testSortTrips()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
    
    
    public function testSortTripss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
    
}
